// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/class/index.ts";
import * as $1 from "./routes/api/schema.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/schema-org-gen/index.tsx";
import * as $$0 from "./islands/Main.tsx";
import * as $$1 from "./islands/Preview.tsx";

const manifest = {
  routes: {
    "./routes/api/class/index.ts": $0,
    "./routes/api/schema.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/schema-org-gen/index.tsx": $3,
  },
  islands: {
    "./islands/Main.tsx": $$0,
    "./islands/Preview.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
