// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/graphql.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/schema-org-gen/index.tsx";
import * as $$0 from "./islands/Form.tsx";
import * as $$1 from "./islands/Main.tsx";
import * as $$2 from "./islands/Preview.tsx";

const manifest = {
  routes: {
    "./routes/graphql.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/schema-org-gen/index.tsx": $2,
  },
  islands: {
    "./islands/Form.tsx": $$0,
    "./islands/Main.tsx": $$1,
    "./islands/Preview.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
